Добавлен обработчик ошибок 403 и 404
it-for-free/SimpleMVC pull request #3
Opened 2020-07-19 15:54 UTC by toyrik

Внесены изменения в классе Router добавлен метод getControllerFIleName для поиска пути до файла
контроллера, в метод callControllerAction добавлена генерация ощибки в случае если файл контроллера не найден.
В классах SmvcAccesException и SmvcRoutingException изменены коды
генерируемых ошибок

2020-08-01 19:43 UTC, vedro-compota requested changes
нужны ещё правки, написал комменты

2020-08-01 19:43 UTC, vedro-compota commented on src/ExceptionHandler.php
> +        foreach ($handlers as $exceptionName => $handlerName){
in_array() не поможет?

2020-08-01 19:43 UTC, vedro-compota commented on src/interfaces/ExceptionsHandler.php
> +     *
комментирии плиз

2020-08-01 19:43 UTC, vedro-compota commented on src/Router.php
>       * @return $this
откатить правки, или объяснить зачем нужно

2020-08-01 19:43 UTC, vedro-compota commented on src/ExceptionHandler.php
> +                $this->displayException($exception);
лучше бросить исключение без обработчика ещё раз

2020-08-07 13:38 UTC, toyrik commented on src/Router.php
>       * @return $this
Если откатить правки то ошибка генерируется в другом месте и не попадает в обработчик

2020-08-07 13:39 UTC, toyrik commented on src/ExceptionHandler.php
> +                $this->displayException($exception);
Поправил

2020-08-15 19:04 UTC, vedro-compota requested changes

2020-08-15 19:04 UTC, vedro-compota commented on src/ExceptionHandler.php
> +class ExceptionHandler implements ExceptionHandlerInterface
менеджер исключений не должен имплементировать этот интерфейс, так как этот интрфейс создан, чтобы быть шаблоном для пользовательских обработчиков.

2020-08-15 19:04 UTC, vedro-compota commented on src/ExceptionHandler.php
> +            $thatHandler->handleException($exception);
перед вызовом метода проверить, что объект реализует интерфейс, а иначе бросить исключение нужного типа

2020-08-16 06:38 UTC, toyrik commented
Поправил

2020-08-19 16:15 UTC, vedro-compota approved these changes

2020-08-19 16:15 UTC, vedro-compota commented on src/Router.php
>       * @return $this
ок

2020-08-19 16:16 UTC, merged