Добавлено объявление типа
it-for-free/SimpleMVC pull request #7
Opened 2023-07-14 21:03 UTC by NewDeveloper111

Добавлено объявление возвращаемого типа функций если нет соответствующего PHPDoc (без параметра return).

2023-07-14 21:22 UTC, vedro-compota commented on src/ExceptionHandler.php
> -    public function handleException(\Exception $exception): void
почему здесь убрано возращаемое значение?

2023-07-14 21:22 UTC, vedro-compota commented on src/Router.php
>      private function getControllerFileName($controllerName)
перенести тип в код

2023-07-14 21:22 UTC, vedro-compota commented on src/Router.php
> +    public function getControllerMethodName($action): string
а тип для входящего параметра?

2023-07-17 17:59 UTC, vedro-compota commented on src/Application.php
> -    protected static function isAlias($param)
Давайте сделаем чтобы boolean возвращался всегда

2023-07-17 18:02 UTC, vedro-compota requested changes
Нужны правки

2023-07-17 18:03 UTC, vedro-compota commented on src/Application.php
> -    protected static function isAlias($param)
Давайте сделаем чтобы boolean возвращался всегда

2023-07-19 17:07 UTC, vedro-compota commented on src/Router.php
>       * @param type $action -- строка GET-параметр
Укажем тип string (можно проверить предварительно) - и в phpdoс

2023-07-20 08:21 UTC, NewDeveloper111 commented on src/Application.php
> -    protected static function isAlias($param)
Исправлено.

2023-07-20 08:22 UTC, NewDeveloper111 commented on src/Router.php
>       * @param type $action -- строка GET-параметр
Исправлено.

2023-07-20 08:24 UTC, NewDeveloper111 commented on src/Router.php
>      private function getControllerFileName($controllerName)
Исправлено.

2023-07-21 16:53 UTC, merged